Fix startup scripts
Signed-off-by: 建辉 <809205580@qq.com>

diff --git a/ubuntu/xterminal.init b/ubuntu/xterminal.init
--- a/ubuntu/xterminal.init
+++ b/ubuntu/xterminal.init
@@ -1,71 +1,46 @@
-#!/bin/sh
-
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides:          xterminal
-# Required-Start:    $network $local_fs $remote_fs
-# Required-Stop:     $network $local_fs $remote_fs
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Should-Start:      slapd cups
-# Should-Stop:       slapd cups
-# Short-Description: start xterminal daemon
+# Provides:			xterminal_broker
+# Required-Start:	$remote_fs $syslog
+# Required-Stop:	$remote_fs $syslog
+# Default-Start:	2 3 4 5
+# Default-Stop:		0 1 6
+# Short-Description: Execute the xterminal_broker command.
+# Description:
 ### END INIT INFO
 
-XTERMINALPID=/var/run/xterminal.pid
-
-# clear conflicting settings from the environment
-unset TMPDIR
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
 
 . /lib/lsb/init-functions
 
-case $1 in
-	start)
-		if init_is_upstart; then
-			exit 1
-		fi
-		
-		log_daemon_msg "Starting xterminal daemon" xterminal
+XTERMINALPID=/var/run/xterminal.pid
 
-		if ! start-stop-daemon --start --quiet --oknodo --make-pidfile --pidfile $XTERMINALPID --background --exec /usr/sbin/xterminal_broker.lua; then
-			log_end_msg 1
-			exit 1
-		fi
+do_start () {
+	start-stop-daemon --start --make-pidfile --pidfile $XTERMINALPID --background --exec /usr/sbin/xterminal_broker
+}
 
-		log_end_msg 0
-		;;
-	stop)
-		if init_is_upstart; then
-			exit 0
-		fi
+do_stop () {
+	start-stop-daemon --stop --pidfile $XTERMINALPID
+	sleep 1
+	rm -f $XTERMINALPID
+}
 
-		log_daemon_msg "Stopping xterminal daemon" xterminal
-
-		start-stop-daemon --stop --quiet --pidfile $XTERMINALPID
-		# Wait a little and remove stale PID file
-		sleep 1
-		if [ -f $XTERMINALPID ] && ! ps h `cat $XTERMINALPID` > /dev/null
-		then
-			rm -f $XTERMINALPID
-		fi
-
-		log_end_msg 0
-		;;
-	reload|restart|force-reload)
-		if init_is_upstart; then
-			exit 1
-		fi
-		$0 stop
-		sleep 1
-		$0 start
-		;;
-	status)
-		status_of_proc -p $XTERMINALPID /usr/sbin/xterminal_broker.lua xterminal_broker.lua
-		exit $?
-		;;
-	*)
-		echo "Usage: /etc/init.d/smbd {start|stop|reload|restart|force-reload|status}"
-		exit 1
-		;;
+case "$1" in
+  start)
+	do_start
+	;;
+  stop)
+	do_stop
+	;;
+  restart|reload|force-reload)
+	echo "Error: argument '$1' not supported" >&2
+	exit 3
+	;;
+  status)
+	exit 0
+	;;
+  *)
+	echo "Usage: $0 start|stop" >&2
+	exit 3
+	;;
 esac
-
-exit 0
